services:
  - type: web
    name: hireahero
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hireahero.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: hireahero.onrender.com
