services:
  - type: web
    name: hireahero
    runtime: python  # ✅ required field, was missing
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hireahero.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: superhero-database.onrender.com
      - key: DEBUG
        value: "False"  # ✅ must be a string (not boolean) for YAML
