# Generated by Django 5.2 on 2025-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_cartitem_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
    ]
